# Generated by Django 2.2.5 on 2019-10-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Изделие')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTruck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_parts_app.Product')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_parts_app.Truck')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='trucks',
            field=models.ManyToManyField(through='truck_parts_app.ProductTruck', to='truck_parts_app.Truck'),
        ),
    ]
